const products = [
  {
    _id: '1',
    name: 'Toddler Sweater',
    image: '/images/toddler-sweater.jpg',
    description:
      'Toddler Striped Sweater With Hood Isolated On White Stock Photo',
    brand: 'Apple',
    category: 'Electronics',
    price: 19.99,
    countInStock: 10,
    rating: 4.5,
    numReviews: 12,
  },
  {
    _id: '2',
    name: 'White Baby Bodysuit',
    image: '/images/white-baby-bodysuit.jpg',
    description:
      'Top view white baby bodysuit with long sleeve on wooden background',
    brand: 'Apple',
    category: 'Electronics',
    price: 15.99,
    countInStock: 7,
    rating: 4.0,
    numReviews: 8,
  },
  {
    _id: '3',
    name: 'Bodysuit Socks',
    image: '/images/bodysuit-socks.jpg',
    description:
      'pink bodysuit and tiny socks',
    brand: 'Cannon',
    category: 'Electronics',
    price: 4.99,
    countInStock: 5,
    rating: 3,
    numReviews: 12,
  },
  {
    _id: '4',
    name: 'Baby Sleeper',
    image: '/images/baby-sleeper.jpg',
    description:
      'Cotton baby sleeper isolated',
    brand: 'Sony',
    category: 'Electronics',
    price: 10.99,
    countInStock: 11,
    rating: 5,
    numReviews: 12,
  },
  {
    _id: '5',
    name: 'Baby Pyjamas',
    image: '/images/baby-pyjamas.jpg',
    description:
      'Baby boy blue pyjamas',
    brand: 'Logitech',
    category: 'Electronics',
    price: 20.99,
    countInStock: 7,
    rating: 3.5,
    numReviews: 10,
  },
  {
    _id: '6',
    name: 'Baby Cloth',
    image: '/images/baby-cloth.jpg',
    description:
      'Baby cloth in blue color',
    brand: 'Amazon',
    category: 'Electronics',
    price: 16.99,
    countInStock: 0,
    rating: 4,
    numReviews: 12,
  },
  {
    _id: '7',
    name: ' Baby Socks',
    image: '/images/baby-socks.jpg',
    description:
      ' Baby socks on white stock photo',
    brand: 'Amazon',
    category: 'Electronics',
    price: 5.99,
    countInStock: 0,
    rating: 4,
    numReviews: 12,
  },
  {
    _id: '8',
    name: ' Baby Booties',
    image: '/images/baby-booties.jpg',
    description:
      '  A pair of handmade blue knitted baby booties, isolated on white background',
    brand: 'Amazon',
    category: 'Electronics',
    price: 9.99,
    countInStock: 0,
    rating: 4,
    numReviews: 12,
  },
]

export default products
